# 未來在伺服器啟動時指定 -Dspring.profiles.active=dev 就會載入這份
spring:
  # 如果雲端測試機的資料庫 IP 不同，可以在這裡覆蓋 url
  # datasource:
  #   url: jdbc:postgresql://your-dev-db-ip:5432/classcord

  # 正式對接雲端 Resend 服務
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${SPRING_MAIL_PASSWORD} # 密碼用變數封印，上雲端時由系統環境變數注入
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true