spring:
  application:
    name: classcord-backend

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/classcord?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  threads:
    virtual:
      enabled: true # 開啟 Spring Boot 的虛擬執行緒支持

  jpa:
    open-in-view: false # 關閉 Open Session in View，防止資料庫連線洩漏與隱蔽的 N+1
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true # 由於使用 UUID v7，也能享受批次 INSERT 的效能優化

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3         # 最多重試 3 次
          initial-interval: 1000ms # 第一次重試等 1 秒
          multiplier: 2.0         # 每次重試加倍等待 (1s -> 2s -> 4s)
          max-interval: 5000ms    # 最長等待 5 秒

logging:
  level:
    root: INFO
    com.hys.classcord: DEBUG
    org.hibernate.SQL: DEBUG  # 在主控台顯示 SQL 語法
    org.hibernate.orm.jdbc.bind: TRACE # 顯示 SQL 傳入的真實變數數值

app:
  jwt: # 可能也可以抽成一個properties類
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: 86400000 # 24小時以毫秒計算
  urls:
    backend: http://localhost:8080
    frontend: http://localhost:3000
  mail:
    from-email: noreply@email.com
  # 儲存相關設定
  storage:
    endpoint: ${S3_ENDPOINT}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
    public-url: ${S3_PUBLIC_URL}
    # 限制額度 (單位：Bytes)
    system-quota: 9126805504   # 8.5 GB
    server-quota: 524288000    # 500 MB
