spring:
  application:
    name: classcord-backend

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/classcord?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false # 關閉 Open Session in View，防止資料庫連線洩漏與隱蔽的 N+1
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true # 由於使用 UUID v7，也能享受批次 INSERT 的效能優化

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt: # 可能也可以抽成一個properties類
    secret-key: ${JWT_SECRET_KEY}
    expiration-ms: 86400000 # 24小時以毫秒計算
  urls:
    backend: http://localhost:8080
    frontend: http://localhost:3000