apiVersion: v1
data:
  APP_BACKEND_URL: https://api-classcord.hys-lab.com
  APP_FRONTEND_URL: https://classcord.hys-lab.com
  CORS_ALLOWED_ORIGINS: https://classcord.hys-lab.com
  DROPLET1_PRIVATE_IP: 10.104.0.4
  DROPLET2_PRIVATE_IP: 10.104.0.2
  NACOS_DISCOVERY_IP: 10.104.0.2
  NACOS_NAMESPACE: prod
  NACOS_SERVER_ADDR: nacos:8848
  S3_BUCKET_NAME: classcord
  S3_ENDPOINT: https://s3.us-west-004.backblazeb2.com
  S3_PUBLIC_URL: ""
  SEATA_SERVER_ADDR: 10.104.0.4:8091
  SENTINEL_DASHBOARD_ADDR: 10.104.0.4:8858
  SPRING_CLOUD_SENTINEL_EAGER: "true"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATA_REDIS_HOST: 10.104.0.4
  SPRING_DATASOURCE_URL: jdbc:postgresql://10.104.0.4:5432/classcord?reWriteBatchedInserts=true&options=-c%20lock_timeout=2000ms
  SPRING_RABBITMQ_HOST: 10.104.0.4
kind: ConfigMap
metadata:
  name: ai-service-config
  namespace: classcord
